backend:
  name: github
  repo: jjmarm/masksforhunger
media_folder: static/assets
public_folder: /assets
collections:
  - name: catalog
    label: Mask
    folder: catalog
    slug: "{{slug}}"
    create: true
    fields:
      - { name: title, label: Title }
      - { name: image, label: Image, widget: image }
      - { name: quantity, label: Quantity Remaining, widget: number }
